# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'index' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #-- OC库
#pod 'MBProgressHUD'
pod 'SVProgressHUD'
pod 'MJRefresh'

  # Pods for index
pod 'Alamofire'
pod 'SnapKit'
pod 'Kingfisher'
pod 'SwiftyJSON'
pod 'Moya'
pod 'HandyJSON'
pod 'pop'

end
